trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'azure-linux-vm-ssh'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: |
      website/**
      scripts/**
    targetFolder: '/home/azureuser/deployment'

- task: SSH@0
  inputs:
    sshEndpoint: 'azure-linux-vm-ssh'
    runOptions: 'commands'
    commands: |
       pwd
       ls -la /home/azureuser/deployment/scripts