trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'azure-linux-vm-ssh'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: |
      scripts/deploy.sh
      Website/index.html
    targetFolder: '~/deployment'

- task: SSH@0
  inputs:
    sshEndpoint: 'azure-linux-vm-ssh'
    runOptions: 'commands'
    commands: |
       echo "Checking deployment files"
       ls -R ~/deployment
       chmod +x ~/deployment/scripts/deploy.sh
       bash ~/deployment/scripts/deploy.sh